### ISSUE TITLE
Pull in pyocclient from upstream repo

### ISSUE THREAD

**Issue by PVince81** [owncloud/smashbox#1]
Instead of having pyocclient hard-coded into this repo, it should get pulled from upstream https://github.com/PVince81/pyocclient

One idea would be using pip, but that limits it to the latest released version.
Maybe there's a better way.

**Comment by MorrisJobke** [comment]
> One idea would be using pip, but that limits it to the latest released version.
> Maybe there's a better way.

That's not a limitation but an advantage. You never want to rely on some version. Because a version brings you a stable API. ;)

**Comment by PVince81** [comment]
Can pip work like composer and point to a specific revision ?

In some cases while developing unit tests one might want to use the upstream master version instead of the latest released one (master version which might contain unreleased new API calls that talk to yet unreleased OC APIs like favorites/provisioning API)

**Comment by MorrisJobke** [comment]
@PVince81 I don't know that much about pip. :(

**Comment by PVince81** [comment]
@Gomez what do you think ?

**Comment by MorrisJobke** [comment]
It looks so https://pip.pypa.io/en/latest/user_guide.html#requirements-files - see point 4

**Comment by Gomez** [comment]
Correct, pip can handle this.

Even better would be depend on release from https://pypi.python.org/pypi/pyocclient/ and handle it with a requirements.txt. 

Releases to pypi can be done easy with tools like:
https://pypi.python.org/pypi/zest.releaser

**Comment by PVince81** [comment]
Thing is we're not that fast at releasing new versions :smile: 

And also it doesn't make much sense to release a pyocclient version with the "favorites" API for example if the matching OC version hasn't been released either. But still, this project here (smashbox / automated tests) might need these new API calls. So it probably makes sense to make it depend on upstream master.

**Comment by PVince81** [comment]
Thinking of doing it with a git submodule. Goal is to be able to keep in sync with master, not specific releases, as some unreleased calls might be put into pyocclient for unreleased OC versions.
