### ISSUE TITLE
[Framework] setting runid still appends id number to user name even when oc_account_runid_enabled is set to false

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/smashbox#103]
When using runid in the smashbox.conf as a way to retain results from from each testset run, the smasbox framework tries to append the runid to the user name even when oc_account_runid_enabled is set to False.

**Comment by nickvergessen** [comment]
Works just fine for me, are you having problems with a new test?
I fixed one test 2 weeks ago, please make sure you didn't copy the bad code:
https://github.com/owncloud/smashbox/pull/90/files

**Comment by nickvergessen** [comment]
If the issue is another issue then the one named above, feel free to reopen
