### ISSUE TITLE
Bringing oc/smashbox in line with cernbox again

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/smashbox#118]
### Suggested idea
1. Rename current master to master-owncloud
2. Recreate master based on cernbox/master
3. Bring all the test files from master-owncloud to our new master
4. Do not allow modifications in other files then lib/oc-tests/
5. Create a new owncloud-util class/module where we put our util methods, so our util class is still the one from cernbox
6. When a method in cernbox-util needs updating: copy to oc-util and change as desired and send patch to cernbox, once merged there, upload owncloud/master and remove the local wrapping method. Alternatively we can also just send the PR upstream, if the method is not blocking our testing.

This allows to have a clean cernbox..owncloud/smashbox comparison and to only have new files in owncloud/smashbox..cernbox comparison, so we can cleanly update our copy with cernbox changes all the time and can easily bring our changes upstream.

Fix #113 
Fix #68

**Comment by MorrisJobke** [comment]
Or better: Just maintain the tests in this repo and load smashbox as an dependency (maybe as a true fork where PRs are started from and the package manager can fetch patched versions from) ;)

Then there is no way to "accidentially" diverge again.

Anyway: Many thanks for the initiative :+1:

**Comment by moscicki** [comment]
@nickvergessen: this sounds entirely reasonable. If this is implemented as you suggest then I will be able to automatically merge all pull requests that are in your part of the project (oc-tests and oc-util). Of course on your side you need to decide what you want to have merged in the upstream smashbox project (and possibly make sure that pull requests are already peer-reviewed or done by a designated person). For changes which are in common I will handle the pull requests with the review on my side. Do you need any special setup from my side that would make it easier for you pull the common changes in the opposite direction i.e. to pull changes in the common smashbox core from the upstream back to your repository (e.g. some tagging or such)?

**Comment by jospoortvliet** [comment]
reference these then ;-)
https://github.com/cernbox/smashbox/pull/24
https://github.com/cernbox/smashbox/pull/25
https://github.com/cernbox/smashbox/pull/26
https://github.com/cernbox/smashbox/pull/27

**Comment by nickvergessen** [comment]
@jospoortvliet the collection of upstream PRs is in https://github.com/owncloud/smashbox/issues/68

**Comment by jospoortvliet** [comment]
@nickvergessen thanks

**Comment by nickvergessen** [comment]
Completed

**Comment by jospoortvliet** [comment]
rocking!
