### ISSUE TITLE
Test needed for php://input bug detection

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/smashbox#128]
The test should perform the equivalent of the following raw HTTP requests:

```
PUT /oc-root/remote.php/webdav/somewhere.txt HTTP/1.1
Content-Type: application/json
Content-Length: 8

testing
```

```
PUT /oc-root/remote.php/webdav/somewhere.txt HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 8

testing
```

On a broken server, these will fail with 400 Bad Request (expected filesize 8, got 0). On PHP 5.6 and above, or with a fixed server (PR not available at time of writing), these will succeed (with either Created or No Content depending if the file was already there or not before hand).

**Comment by nickvergessen** [comment]
Kind of difficult, we only use pyoc client and oc command line client

**Comment by RobinMcCorkell** [comment]
I thought the protocol tests do some raw WebDAV stuff? They depend on pycurl of course...
