### ISSUE TITLE
testcase: cancel and reshare

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/smashbox#14]
From https://github.com/owncloud/core/issues/13216

log in with admin
create a folder "lol"
go into "lol" and create a text file "lol_lol.txt"
share the folder "lol" with user1
log in with user1
tag folder "lol" and file "lol_lol.txt" as favorite
log in with admin
cancel sharing "lol" with user1
log in user1, and check --"lol" is gone
log in with admin and share "lol" with user1 again
log in as user1 and check

**Comment by jnfrmarks** [comment]
Included both single server sharing and federated server sharing

**Comment by nickvergessen** [comment]
The behaviour is actually intended
