### ISSUE TITLE
testcase: shares and renaming

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/smashbox#15]
From https://github.com/owncloud/core/issues/13330:

Create two users "user1" and "user2"
Login as "user2"
Create a folder "test" and share it with "user1"
Login as "user1"
Create a folder "sub"
Upload a huge file "huge.dat" into "sub"
Prepare two cadaver sessions for "user1" (webdav clients)
In cadaver1: "mv sub test" (this will move the huge file into the shared folder) 9: During the copy, in cadaver2 rename the target folder: "mv test/sub test/x"

**Comment by jnfrmarks** [comment]
renaming both folder and files.  From https://github.com/owncloud/core/issues/11795

Create a folder "A" in the web UI
Setup the sync client, let it sync
Close the sync client
Copy lots of files inside of the local "A" folder (in my case pictures about 3-7 MB)
Start the sync client and let it upload the files
During the upload, rename "A" to "A2"
Wait until the sync client does its second try

**Comment by nickvergessen** [comment]
The cases are killed by locking and can not work anymore
