### ISSUE TITLE
Use Python's unittest framework for asserts ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/smashbox#2]
I see that smashbox is using its own custom assert functions.
Would be nice to use existing frameworks like Python's unittest framework for asserts and test runs.
See here for an example how it is used to test pyocclient: https://github.com/PVince81/pyocclient/blob/master/owncloud/test/test.py

@jnfrmarks I heard this is running with the robot framework ? Then we need to find out whether robot supports unittest.

CC @Gomez

**Comment by PVince81** [comment]
This is how smashbox seems to be doing asserts: https://github.com/owncloud/smashbox/blob/master/python/smashbox/utilities/__init__.py#L279

It has its own logging facility.

**Comment by jnfrmarks** [comment]
@PVince81 

Is this something we still want to do?  If not, let's close this.

**Comment by PVince81** [comment]
Probably not.
