### ISSUE TITLE
review failing cern tests

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/smashbox#21]
The following tests written by cern are failing in the ownCloud environment and need to be researched/resolved:

[x ] test_concurrentDirMove
[x ] test_concurrentOverwriteFile
[x ] test_filenames
[x ] test_nplusone
[x] test_nplustwo
~~[ ] test_pingpong~~ - Test works
[x ] test_slowwrite
[ x] test_storm
[ x] test_unicodejam
~~[ ] test_users~~ Test removed - users added as part of all tests

**Comment by jnfrmarks** [comment]
test_storm had two issues:
1.  The skeleton files were synced and being added to the number of files created, causing the test to think there were three more files than expected.
2.  The test_storm.py file was incorrectly calculating the filesize property being passed into create_hashfile.

**Comment by jnfrmarks** [comment]
test_slowwrite and test_concurrentOverwriteFile and test_nplusone have identified a difference in the number of csync_journal.db files created.  See https://github.com/owncloud/client/issues/2950.  

The list of files to be ignored needed to be updated.

**Comment by jnfrmarks** [comment]
~~test_nplustwo needs to be run with a different property setting for oc_account_reset_procedure.  The automated test scripts have been updated.~~

The test was modified to create the users from a different worker.

**Comment by jnfrmarks** [comment]
I've asked for some help from CERN on test_concurrentDirMove:

If I understand the test correctly, the "adder" worker is adding files to a directory "subdir".  While that is going one, "mover" renames "subdir" to "subdir2".  Both workers then sync.  The expectation is that all files created in "subdir" will be in "subdir2".  The test is failing because some of the files are still in "subdir".  I think that is expected behavior because the mover worker is renaming the directory while the adder worker is in the middle of creating files.  Once the directory is moved, any newly created file will be create in the original directory.  The test is expecting all files to be in subdir2 and this is not the case.

**Comment by jnfrmarks** [comment]
@PVince81 
Can you help me out with test_filenames.py and test_unicode?  Both are failing but I'm struggling with the code.

Thanks!

**Comment by PVince81** [comment]
test_concurrentDirMove is basically this issue https://github.com/owncloud/core/issues/11795

**Comment by PVince81** [comment]
test_filenames.py fails on OC 6 too, do we know whether this test has every worked before ?

**Comment by PVince81** [comment]
Hmmm but one thing I see is that there are more failing cases on master than there were on OC 6.

**Comment by jnfrmarks** [comment]
I don't know the history of this test.  It's from CERN.

**Comment by PVince81** [comment]
These are failing on stable6, stable7:

```
2015-03-17 16:35:21,205 - ERROR - creator - some files lost!
2015-03-17 16:35:21,479 - ERROR - creator - some files lost!
2015-03-17 16:35:21,720 - ERROR - creator - some files lost!
2015-03-17 16:35:31,602 - ERROR - propagator - the file has not been propagated: ' '
2015-03-17 16:35:31,602 - ERROR - propagator - the file has not been propagated: '_chr126_4testfile.dat~'
2015-03-17 16:35:31,603 - ERROR - propagator - the file has not been propagated: '._chr46_6.testfile...dat.'
2015-03-17 16:35:31,603 - ERROR - propagator - the file has not been propagated: '_chr126_5testfile.~dat'
2015-03-17 16:35:31,603 - ERROR - propagator - the file has not been propagated: '._chr46_3testfile..dat'
2015-03-17 16:35:31,603 - ERROR - propagator - the file has not been propagated: '~_chr126_6~testfile~.~dat~'
2015-03-17 16:35:31,603 - ERROR - propagator - the file has not been propagated: '~'
2015-03-17 16:35:32,606 - ERROR - propagator - 7 error(s) reported
2015-03-17 16:35:32,609 - ERROR - creator - 3 error(s) reported
```

Not sure why.
On master there's more, so I'll try and find out why, maybe to reduce it back to what it was before.

**Comment by PVince81** [comment]
Raised a ticket in core to look into them (I also posted the results there): https://github.com/owncloud/core/issues/14964

**Comment by PVince81** [comment]
This will reduce the test errors back to the number it had in stable8: https://github.com/owncloud/core/pull/14994
And this removes the expected excluded file names: #36 

Next up: looking at test_unicodejam

**Comment by PVince81** [comment]
Solve the fatal error in test_unicodejam output: https://github.com/owncloud/smashbox/pull/37

I have the feeling that this test never worked before, and it seems many unicode chars get mangled already (not a regression but something that never worked in the first place)

**Comment by jnfrmarks** [comment]
Looks like we've assessed all tests. I'll close this and open issues for any specific failures that need to be addressed.
