### ISSUE TITLE
Consider to remove the "-e" flag in the requirements.txt file

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/smashbox#40]
I've made an installation of smashbox as root. The problem is that other users won't be able to run smashbox because the "owncloud" python package isn't found (the only one that finds the package is the root user)

Looks like the -e flag in the requirements.txt file makes the installer to install a link to where the package is installed and it's not accessible by the rest of users.

After reinstalling the package without the -e flag, I've been able to run smashbox with a standard account

**Comment by jnfrmarks** [comment]
@jvillafanez 

I think that this is resolved now.  Can you please confirm and close?  I now pull the repo from a public place.

**Comment by jvillafanez** [comment]
Any change I should look for? I've checked the requirements.txt flle in the master and develop branches and the flag is still there.

**Comment by nickvergessen** [comment]
If this is still an issue for you, please report and fix at cernbox
