### ISSUE TITLE
scrape_log_file consider the scp port to be 22, which might not be true

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/smashbox#46]
Checking against a dockerized OC instance, mapping the docker ssh port to the external 10022 port, the test "test_scrapeLogFile.py" tries to connect to localhost:22 (ssh host port) instead of localhost:10022 (ssh external docker port).

The affected code line seems to be https://github.com/owncloud/smashbox/blob/master/python/smashbox/utilities/__init__.py#L492 as it uses the default port to copy the file

**Comment by jnfrmarks** [comment]
PR #57 solves this.

@jvillafanez

**Comment by nickvergessen** [comment]
PR has been merged, closing
