### ISSUE TITLE
Update testing

### ISSUE THREAD

**Issue by PVince81** [owncloud/smashbox#54]
Not sure how, but if smashbox could automatically setup ownCloud instances (or could use docker ones) it could feed it with data, then update it to the next version and run the whole test suite on it to see if everything still works (ex: shares not broken, etc)

**Comment by SergioBertolinSG** [comment]
Branch smashbox_plus_docker in owncloud/automated-tests/scripts/smashboxPlusDockerTests.py (Pending to be reviewed at the moment)
Should do the job.

**Comment by nickvergessen** [comment]
@jvillafanez added tests somewhere for the update.
So I'm closing this
