### ISSUE TITLE
runcmd requires refactoring

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/smashbox#58]
runcmd uses Popen with a string and the parameter "shell = True" by default. This is a security risk because someone could execute wrong commands easily or perform some kind of shell injection.

Consider the function "remove_tree(path)", which execute the runcmd. If path contains a space, it's easy that the command fails because it will execute "rm -rf path1 path2". This could be dangerous with weird paths such as "ppath /" or "/ ppath" as it will try to remove the root folder. It also easy to perform shell injection such as "remove_tree('path1 ; touch /tmp/injected')"

In addition, building a command is usually easier and more readable using a sequence instead of a string, making clear the parameters you're passing. Passing the command as a sequence also takes care of shell injection.

Consider the following example:

```
runcmd('curl -k %s -X DELETE %s '%(config.get('curl_opts',''),oc_webdav_url(remote_folder=path)))
runcmd(['curl', '-k', config.get('curl_opts',''),
                '-X', 'DELETE',
                oc_webdav_url(remote_folder=path)])
```

**Comment by nickvergessen** [comment]
Please report and fix at https://github.com/cernbox/smashbox
