### ISSUE TITLE
bin/smash should not exit with 0 when an error occured

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/smashbox#63]
Currently we only exit with `1` when a fatal_check failed, using
https://github.com/owncloud/smashbox/blob/38e0b9ece17cef5b128821bc6fd3dff88cfa4793/python/smashbox/utilities/__init__.py#L450

``` py
        raise AssertionError(message)
```

However `error_check` does not fail hard. The actual problem is it does not fail in the end as well.
So my suggestion is, that in case we reach the point and display that a user had an error, we set a global variable and exit with `1` after all `worker_wrap` `finally` have been handled.
https://github.com/owncloud/smashbox/blob/a7be42f7cac40e6e1a5c2b86ad66fa5a7589f44f/python/smashbox/multiprocessing_engine.py#L172-L173

``` py
            if smashbox.utilities.reported_errors:
               logger.error('%s error(s) reported',len(smashbox.utilities.reported_errors))
```

This is required, because otherwise travis reports that everything went well, although it didn't:
https://travis-ci.org/nickv-oc/smashbox/builds/58448317#L631-L636

@PVince81 python expert, can you help please :grinning:

**Comment by nickvergessen** [comment]
There is already code which set's the global exit code, so setting `global_exitcode_error` should do what we need:
https://github.com/owncloud/smashbox/blob/6a2db3f31e593fb15e4e16778eab3a0091ca0483/bin/smash#L159-L164

``` py
global_exitcode_error = True
```

https://github.com/owncloud/smashbox/blob/6a2db3f31e593fb15e4e16778eab3a0091ca0483/bin/smash#L227-L228

``` py
   if global_exitcode_error:
      sys.exit(global_exitcode_error)
```

**Comment by PVince81** [comment]
Ha, you didn't dig deep enough :wink:
